# Env Options
sudo: required
dist: xenial

# Language Options
language: go

# Service Options
services:
  - docker

go:
  - 1.9.3
  - 1.9.4
  - "1.10"
  - 1.10.1
  - 1.10.3
  - "1.11"
  - "1.11.1"
  - "1.11.2"
  - master
  - tip

before_install:
  - sudo apt-get update -qqy
  - sudo apt-get autoremove -qqy
  - sudo apt-get install -qqy upx golang-go
  - sudo docker pull junland/gccgo:v1

before_script:
  - go version
  - echo "#/bin/bash" > /usr/bin/gccgo
  - echo "sudo docker run -it junland/gccgo:v1" >> /usr/bin/gccgo && chmod +x /usr/bin/gccgo
  - go get -t ./...

script:
  - make travis-sizes
