# Env Options
sudo: required
dist: xenial

# Language Options
language: go

# Service Options
services:
  - docker

go:
  - 1.9.4
  - 1.10.3
  - 1.11.1
  - 1.11.2
  - 1.11.3
  - 1.11.4
  - master
  - tip

before_install:
  - sudo echo "deb http://archive.ubuntu.com/ubuntu/ cosmic universe" >> /etc/apt/sources.list
  - sudo echo "deb http://archive.ubuntu.com/ubuntu/ cosmic main restricted" >> /etc/apt/sources.list
  - sudo apt-get update -qqy
  - sudo apt-get install -qqy upx golang-go gccgo
  - sudo apt-get autoremove -qqy

before_script:
  - gccgo -v 
  - go get -t ./...

script:
  - make travis-sizes
