# Env Options
sudo: required
dist: bionic

# Language Options
language: go

go:
  - 1.9.3
  - 1.9.4
  - "1.10"
  - 1.10.1
  - 1.10.3
  - "1.11"
  - "1.11.1"
  - "1.11.2"
  - master
  - tip

before_install:
  - sudo apt-get update -qqy
  - sudo apt-get dist-upgrade -qqy
  - sudo apt-get autoremove -qqy
  - sudo apt-get install -qqy upx golang-go gccgo

before_script:
  - go get -t ./...

script:
  - make travis-sizes
